name: Release

on:
  workflow_dispatch:

jobs:
  # build-docker-image:
  #   needs: check
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   env:
  #     dockerImage: europe-west1-docker.pkg.dev/personalweb-279207/stefanpuia/anysub
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Docker Login
  #       env:
  #         DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  #       run: echo $DOCKER_PASSWORD | docker login -u _json_key --password-stdin https://europe-west1-docker.pkg.dev

  #     - name: Docker Build
  #       run: DOCKER_BUILDKIT=1 docker build -f ./Dockerfile -t "${{ env.dockerImage }}:build-${{ github.run_id }}" -t "${{ env.dockerImage }}:latest" .

  #     - name: Docker Push
  #       run: docker image push --all-tags "${{ env.dockerImage }}"

  release:
    env:
      PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
    # needs:
    #   - build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://StefanPuia:$PRIVATE_TOKEN@github.com/StefanPuia/anysub.git
      - run: yarn install
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
